In [2]:
import duckdb
from pathlib import Path

In [ ]:
DATA_DIR = Path("../data/raw")
# Path to the DuckDB database file

In [4]:
con = duckdb.connect("../northwind.duckdb")

In [5]:
list(DATA_DIR.glob("*.csv"))

[WindowsPath('../data/raw/categories.csv'),
 WindowsPath('../data/raw/customers.csv'),
 WindowsPath('../data/raw/employees.csv'),
 WindowsPath('../data/raw/orders.csv'),
 WindowsPath('../data/raw/order_details.csv'),
 WindowsPath('../data/raw/products.csv'),
 WindowsPath('../data/raw/shippers.csv')]

In [6]:
con.sql("""
SELECT *
FROM read_csv_auto('../data/raw/categories.csv')
"""
).df()

,categoryID,categoryName,description
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales"
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an..."
2,3,Confections,"Desserts, candies, and sweet breads"
3,4,Dairy Products,Cheeses
4,5,Grains & Cereals,"Breads, crackers, pasta, and cereal"
5,6,Meat & Poultry,Prepared meats
6,7,Produce,Dried fruit and bean curd
7,8,Seafood,Seaweed and fish

In [7]:
con.sql("""
SELECT *
FROM read_csv_auto(
    '../data/raw/customers.csv',
    encoding = 'latin-1'
);
""").show()

┌────────────┬────────────────────────────────────┬─────────────────────────┬───────────────────────────┬─────────────┬─────────┐
│ customerID │            companyName             │       contactName       │       contactTitle        │    city     │ country │
│  varchar   │              varchar               │         varchar         │          varchar          │   varchar   │ varchar │
├────────────┼────────────────────────────────────┼─────────────────────────┼───────────────────────────┼─────────────┼─────────┤
│ ALFKI      │ Alfreds Futterkiste                │ Maria Anders            │ Sales Representative      │ Berlin      │ Germany │
│ ANATR      │ Ana Trujillo Emparedados y helados │ Ana Trujillo            │ Owner                     │ Mexico City │ Mexico  │
│ ANTON      │ Antonio Moreno Taquería            │ Antonio Moreno          │ Owner                     │ Mexico City │ Mexico  │
│ AROUT      │ Around the Horn                    │ Thomas Hardy            │ Sales Representative      │ London      │ UK      │
│ BERGS      │ Berglunds snabbköp                 │ Christina Berglund      │ Order Administrator       │ Luleå       │ Sweden  │
│ BLAUS      │ Blauer See Delikatessen            │ Hanna Moos              │ Sales Representative      │ Mannheim    │ Germany │
│ BLONP      │ Blondesddsl père et fils           │ Frédérique Citeaux      │ Marketing Manager         │ Strasbourg  │ France  │
│ BOLID      │ Bólido Comidas preparadas          │ Martín Sommer           │ Owner                     │ Madrid      │ Spain   │
│ BONAP      │ Bon app'                           │ Laurence Lebihan        │ Owner                     │ Marseille   │ France  │
│ BOTTM      │ Bottom-Dollar Markets              │ Elizabeth Lincoln       │ Accounting Manager        │ Tsawassen   │ Canada  │
│   ·        │           ·                        │       ·                 │        ·                  │    ·        │  ·      │
│   ·        │           ·                        │       ·                 │        ·                  │    ·        │  ·      │
│   ·        │           ·                        │       ·                 │        ·                  │    ·        │  ·      │
│ TRAIH      │ Trail's Head Gourmet Provisioners  │ Helvetius Nagy          │ Sales Associate           │ Kirkland    │ USA     │
│ VAFFE      │ Vaffeljernet                       │ Palle Ibsen             │ Sales Manager             │ Århus       │ Denmark │
│ VICTE      │ Victuailles en stock               │ Mary Saveley            │ Sales Agent               │ Lyon        │ France  │
│ VINET      │ Vins et alcools Chevalier          │ Paul Henriot            │ Accounting Manager        │ Reims       │ France  │
│ WANDK      │ Die Wandernde Kuh                  │ Rita Müller             │ Sales Representative      │ Stuttgart   │ Germany │
│ WARTH      │ Wartian Herkku                     │ Pirkko Koskitalo        │ Accounting Manager        │ Oulu        │ Finland │
│ WELLI      │ Wellington Importadora             │ Paula Parente           │ Sales Manager             │ Resende     │ Brazil  │
│ WHITC      │ White Clover Markets               │ Karl Jablonski          │ Owner                     │ Seattle     │ USA     │
│ WILMK      │ Wilman Kala                        │ Matti Karttunen         │ Owner/Marketing Assistant │ Helsinki    │ Finland │
│ WOLZA      │ Wolski  Zajazd                     │ Zbyszek Piestrzeniewicz │ Owner                     │ Warszawa    │ Poland  │
└────────────┴────────────────────────────────────┴─────────────────────────┴───────────────────────────┴─────────────┴─────────┘
  91 rows (20 shown)                                                                                                  6 columns

In [ ]:
# Create tables in DuckDB from the CSV files
con.sql("""
CREATE OR REPLACE TABLE customers AS
SELECT *
FROM read_csv('../data/raw/customers.csv',
        encoding = 'latin-1'
        );
""")

con.sql("""
CREATE OR REPLACE TABLE categories AS
SELECT *
FROM read_csv_auto('../data/raw/categories.csv');
""")

con.sql("""
CREATE OR REPLACE TABLE employees AS
SELECT *
FROM read_csv_auto('../data/raw/employees.csv');
""")

con.sql("""
CREATE OR REPLACE TABLE order_details AS
SELECT *
FROM read_csv_auto('../data/raw/order_details.csv');
""")

con.sql("""
CREATE OR REPLACE TABLE orders AS
SELECT *
FROM read_csv_auto('../data/raw/orders.csv');
""")

con.sql("""
CREATE OR REPLACE TABLE products AS
SELECT *
FROM read_csv_auto('../data/raw/products.csv', encoding = 'latin-1');
""")

con.sql("""
CREATE OR REPLACE TABLE shippers AS
SELECT *
FROM read_csv_auto('../data/raw/shippers.csv');
""")

In [12]:
#check that the tables were created successfully
con.sql("""
    SHOW TABLES; """  ).df()

            name
0     categories
1      customers
2      employees
3  order_details
4         orders
5       products
6       shippers

In [ ]:
con.sql("""
        SELECT COUNT(*) as customer_count FROM customers;""").df()

con.sql("""
        SELECT COUNT(*) as customer_count FROM customers;""").df()

   count_star()
0            91